"use client";

import { useEffect, useState } from "react";
import axios from "axios";
import Image from "next/image";
import { useAuth } from "@/hooks/useAuth";
import toast from "react-hot-toast";
import { MdSearch, MdReplay, MdPictureAsPdf } from "react-icons/md";
import { AssetRequest } from "@/types";

export default function MyAssetsPage() {
  const { authHeaders } = useAuth();
  const [requests, setRequests] = useState<AssetRequest[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pages, setPages] = useState(1);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page: String(page), limit: "10" });
      if (search) params.append("search", search);
      if (statusFilter) params.append("status", statusFilter);
      const res = await axios.get(`/api/requests?${params}`, { headers: authHeaders });
      setRequests(res.data.requests || []);
      setTotal(res.data.total || 0);
      setPages(res.data.pages || 1);
    } catch { toast.error("Failed to load"); }
    finally { setLoading(false); }
  };

  useEffect(() => { if (authHeaders.Authorization) load(); }, [authHeaders, page, search, statusFilter]);

  const handleReturn = async (id: string) => {
    if (!confirm("Return this asset?")) return;
    try {
      await axios.patch(`/api/requests/${id}`, { action: "return" }, { headers: authHeaders });
      toast.success("Asset returned successfully");
      load();
    } catch (err: any) {
      toast.error(err.response?.data?.error || "Return failed");
    }
  };

  const handleCancel = async (id: string) => {
    if (!confirm("Cancel this request?")) return;
    try {
      await axios.delete(`/api/requests/${id}`, { headers: authHeaders });
      toast.success("Request cancelled");
      load();
    } catch { toast.error("Cancel failed"); }
  };

  const handlePrint = (r: AssetRequest) => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Asset Report</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;max-width:600px;margin:auto;}
      h1{color:#4F46E5;}table{width:100%;border-collapse:collapse;}td,th{padding:12px;border:1px solid #e5e7eb;text-align:left;}
      th{background:#f9fafb;}</style></head><body>
      <h1>Asset Report — SCENTICO AssetVerse</h1>
      <table>
        <tr><th>Asset Name</th><td>${r.assetName}</td></tr>
        <tr><th>Type</th><td>${r.assetType}</td></tr>
        <tr><th>Company</th><td>${r.companyName}</td></tr>
        <tr><th>Status</th><td>${r.status}</td></tr>
        <tr><th>Request Date</th><td>${r.requestDate ? new Date(r.requestDate).toLocaleDateString() : "—"}</td></tr>
        <tr><th>Approval Date</th><td>${r.approvalDate ? new Date(r.approvalDate).toLocaleDateString() : "—"}</td></tr>
      </table>
      <p style="margin-top:32px;color:#9ca3af;font-size:12px;">Generated by AssetVerse</p>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  const statusBadge = (s: string) => {
    const map: Record<string, string> = {
      pending: "badge-warning", approved: "badge-success",
      rejected: "badge-error", returned: "badge-info",
    };
    return `badge badge-sm text-white capitalize ${map[s] || "badge-ghost"}`;
  };

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">My Assets</h1>
        <p className="text-gray-500 text-sm mt-1">{total} total requests</p>
      </div>

      <div className="flex gap-3 mb-6">
        <label className="input input-bordered flex items-center gap-2 flex-1 max-w-sm rounded-xl">
          <MdSearch className="w-4 h-4 text-gray-400" />
          <input type="text" placeholder="Search assets..." value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(1); }} className="grow text-sm" />
        </label>
        <select value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value); setPage(1); }}
          className="select select-bordered rounded-xl text-sm">
          <option value="">All Status</option>
          <option value="pending">Pending</option>
          <option value="approved">Approved</option>
          <option value="rejected">Rejected</option>
          <option value="returned">Returned</option>
        </select>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="table">
            <thead className="bg-gray-50 text-gray-600 text-xs uppercase tracking-wider">
              <tr>
                <th className="py-4 px-6">Asset</th>
                <th>Company</th>
                <th>Request Date</th>
                <th>Approval Date</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? Array.from({ length: 5 }).map((_, i) => (
                <tr key={i}>{Array.from({ length: 6 }).map((_, j) => (
                  <td key={j}><div className="h-4 bg-gray-100 rounded animate-pulse w-20" /></td>
                ))}</tr>
              )) : requests.length === 0 ? (
                <tr><td colSpan={6} className="text-center py-12 text-gray-400">No requests yet</td></tr>
              ) : requests.map((r) => (
                <tr key={r._id} className="hover:bg-gray-50 transition-colors">
                  <td className="py-3 px-6">
                    <div className="flex items-center gap-2">
                      {r.assetImage && (
                        <Image src={r.assetImage} alt={r.assetName || ""} width={36} height={36}
                          className="rounded-lg object-cover" unoptimized />
                      )}
                      <div>
                        <p className="text-sm font-medium text-gray-800">{r.assetName}</p>
                        <p className="text-xs text-gray-400 capitalize">{r.assetType}</p>
                      </div>
                    </div>
                  </td>
                  <td className="text-sm text-gray-600">{r.companyName}</td>
                  <td className="text-xs text-gray-400">
                    {r.requestDate ? new Date(r.requestDate).toLocaleDateString() : "—"}
                  </td>
                  <td className="text-xs text-gray-400">
                    {r.approvalDate ? new Date(r.approvalDate).toLocaleDateString() : "—"}
                  </td>
                  <td><span className={statusBadge(r.status)}>{r.status}</span></td>
                  <td>
                    <div className="flex items-center gap-1">
                      {r.status === "approved" && r.assetType === "returnable" && (
                        <button onClick={() => handleReturn(r._id!)}
                          className="btn btn-info btn-xs text-white rounded-lg gap-1">
                          <MdReplay className="w-3 h-3" /> Return
                        </button>
                      )}
                      {r.status === "pending" && (
                        <button onClick={() => handleCancel(r._id!)}
                          className="btn btn-ghost btn-xs text-red-400 rounded-lg">Cancel</button>
                      )}
                      {r.status === "approved" && (
                        <button onClick={() => handlePrint(r)}
                          className="btn btn-ghost btn-xs text-indigo-500 rounded-lg">
                          <MdPictureAsPdf className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {pages > 1 && (
          <div className="flex justify-center items-center gap-2 p-4 border-t border-gray-100">
            {Array.from({ length: pages }, (_, i) => i + 1).map((p) => (
              <button key={p} onClick={() => setPage(p)}
                className={`btn btn-sm rounded-lg ${p === page ? "btn-primary text-white" : "btn-ghost"}`}>{p}</button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
